version: '3'

services:
  asterisk:
    build: ./asterisk
    volumes: 
      - ./recorded_audio:/usr/asterisk/recorded_audio
    ports:
      - "5060:5060/tcp"
      - "5060:5060/udp"
      - "5061:5061/tcp"
      - "5061:5061/udp"
      - "10000:10000/tcp"
      - "10000:10000/udp"
      - "10001:10001/udp"
      - "10001:10001/tcp"
      - "10002:10002/udp"
      - "10002:10002/tcp"
      - "10003:10003/udp"
      - "10003:10003/tcp"
      - "10004:10004/udp"
      - "10004:10004/tcp"
    networks:
      network:
        ipv4_address: 172.33.0.5

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.33.0.0/16
          gateway: 172.33.0.1
